security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }
        # Pour la prod, il faudra passer à un provider basé sur l'entité User :
        # entity_provider:
        #     entity:
        #         class: App\Entity\User
        #         property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory
            # Exemple d'authentification, à adapter selon besoin
            # form_login:
            #     login_path: login
            #     check_path: login
            # logout:
            #     path: logout
            #     target: /

    role_hierarchy:
        ROLE_EMPLOYEE: ROLE_USER
        ROLE_ADMIN: ROLE_EMPLOYEE

    access_control:
        - { path: ^/mon-profil, roles: ROLE_USER }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/trajet/new, roles: ROLE_USER }
        - { path: ^/trajet/\d+/edit, roles: ROLE_USER }
        - { path: ^/reservation, roles: ROLE_USER }
        - { path: ^/review/employee, roles: ROLE_EMPLOYEE }
        - { path: ^/review/moderate, roles: ROLE_EMPLOYEE }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
